import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import AuthProvider from '@/components/auth/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogg',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex w-screen justify-center' >
        <div className={`flex flex-col w-3/4 h-screen justify-between align-middle  ${inter.className}`}>
          <AuthProvider>

            <Navbar />
            {children}

            <Footer />
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
